name: Create ThinkBase.Blazor.Chat nuget package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  WORKING_DIRECTORY: .
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore "${{env.WORKING_DIRECTORY}}/AIComply.Blazor.Chat.csproj" --ignore-failed-sources
    - name: Build
      run: dotnet build "${{env.WORKING_DIRECTORY}}/AIComply.Blazor.Chat.csproj" --configuration Debug --no-restore
    - name: pack
      run: dotnet pack "${{env.WORKING_DIRECTORY}}/AIComply.Blazor.Chat.csproj"  --no-restore --no-build --configuration Debug --include-symbols --output ${{github.workspace}}\output
    - name: push package
      run: dotnet nuget push ${{github.workspace}}\output\*.nupkg  -k ${{secrets.NUGET_APIKEY}} -s "https://api.nuget.org/v3/index.json" 
